dist: trusty
sudo: false

language: php

php:
  - 7.1.32

env:
  global:
    - DB=mysql
  matrix:
    - TEST_TARGET=CIParallelTests1
    - TEST_TARGET=CIParallelTests2
cache:
  bundler : true
  directories:
  - $HOME/.composer/cache/files

services:
  - redis-server
git:
  submodules: false
  lfs_skip_smudge: true
before_script:
  - printenv
  - mkdir build
  - chmod -R 777 ./build
  - pecl channel-update pecl.php.net
  - echo -ne '\n' | pecl install -f apcu
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl channel-update pecl.php.net
  - pecl install msgpack channel://pecl.php.net/msgpack-2.1.2
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer self-update 1.10.15
  - composer install --prefer-dist --no-interaction --no-dev
  - Vendor/bin/browscap-php browscap:convert app/Test/travis/lite_php_browscap.ini
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp;'; fi"
  - cp -f ./app/Config/bootstrap.php.travis ./app/Config/bootstrap.php
  - mkdir -p ./app/tmp/logs
  - chmod -R 777 ./app/tmp/logs
  - echo "<?php
    class DATABASE_CONFIG {
    private \$identities = array(
      'mysql' => array(
        'datasource' => 'Database/Mysql',
        'host' => '127.0.0.1',
        'login' => 'root'
      ),
    );
    public \$default = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'cakephp',
      'prefix' => ''
    );
    public \$test = array(
        'datasource' => 'Database/Sqlite',
        'persistent' => false,
        'database'   => ':memory:',
        'prefix'     => '',
    );
    public \$redis = array(
        'datasource'  => 'Redis.RedisSource',
        'host'        => 'localhost',
        'port'        => 6379,
        'password'    => '',
        'database'    => 0,
        'timeout'     => 0,
        'persistent'  => false,
        'unix_socket' => '',
        'prefix'      => '',
    );
    public \$redis_test = array(
        'datasource'  => 'Redis.RedisSource',
        'host'        => 'localhost',
        'port'        => 6379,
        'password'    => '',
        'database'    => 0,
        'timeout'     => 0,
        'persistent'  => false,
        'unix_socket' => '',
        'prefix'      => 'local:test:',
    );

    public function __construct() {
        \$db = \$_SERVER['DB'];
        \$config = array_merge(\$this->default, \$this->identities[\$db]);
        if (is_array(\$config['database'])) {
          \$config['database'] = \$config['database']['default'];
        }
        \$this->default = \$config;
    }
    }" > app/Config/database.php
  - mkdir -p build/logs
  - cd ./app
  - echo -ne '\n\n' | ./Console/cake schema create

script:
  # if PR, reporting covarage
#TODO 一旦カバレッジ測定やめる。並列処理にする
#  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./Console/cake test app AllTests --stderr --configuration ../phpunit.xml.dist; fi
#  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then ./Console/cake test app AllTests --stderr --coverage-clover ../build/logs/clover.xml --configuration ../phpunit.xml.dist; fi
  - ./Console/cake test app $TEST_TARGET --stderr --configuration ../phpunit.xml.dist

after_script:
#TODO 一旦カバレッジ測定やめる。並列処理にする
#  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then php Vendor/bin/coveralls -v; fi
before_deploy:
#TODO 一旦カバレッジ測定やめる。並列処理にする
#  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then php Vendor/bin/coveralls -v; fi

notifications:
  slack: goalous:JkI6FxdrZDzE1gILR6qTJ69p
  email: false

deploy:
  # Deploying to e2e env after merged develop.
  - provider: opsworks
    access-key-id: $AWS_ACCESS_KEY
    secret-access-key: $AWS_SECRET_KEY
    # Set e2e stack's cake app-id
    # https://console.aws.amazon.com/opsworks/home?region=ap-northeast-1#/stack/2ac1d699-6382-4b2b-ac1b-a3b962d2df8e/apps/b211b084-022b-4bc1-b5c6-80721b608442
    app-id: b211b084-022b-4bc1-b5c6-80721b608442
    wait-until-deployed: true
    region: ap-northeast-1
    on:
      branch: develop
      # Travis CI is running on parallel, deploy may also run in parallel.
      # Condition below limit the deploy to run only on CIParallelTests1 process.
      condition: "$TEST_TARGET = CIParallelTests1"

## 本番、ISAO環境においては自動deployをやめる。
#  - provider: opsworks
#    access-key-id: $AWS_ACCESS_KEY
#    secret-access-key: $AWS_SECRET_KEY
#    app-id: 77c4fc53-40c3-4a73-b532-18d5ef1beff7
#    wait-until-deployed: true
#    on:
#      branch: master
#  - provider: opsworks
#    access-key-id: $AWS_ACCESS_KEY
#    secret-access-key: $AWS_SECRET_KEY
#    app-id: 786fd3c0-1b5f-49d9-b707-27dba2909c84
#    wait-until-deployed: true
#    on:
#      branch: master-isao
#  - provider: opsworks
#    access-key-id: $AWS_ACCESS_KEY
#    secret-access-key: $AWS_SECRET_KEY
#    app-id: 2481ef12-126f-404c-87da-82fa72097f3b
#    wait-until-deployed: false
#    region: ap-northeast-1
#    on:
#      branch: stage
