language: php

php:
  - 5.5

#services:
#  - sqlite3

cache:
  - bundler
  - apt
  - composer
cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/apcu-4.0.2
  - $HOME/redis-2.2.7
services:
  - redis-server
git:
  submodules: false
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi autoconf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - mkdir build
  - chmod -R 777 ./build
  - cp app/Test/travis/travis-ci-apache build/travis-ci-apache
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo apt-get install php5-xdebug php5-curl php5-mcrypt sqlite3 php5-sqlite
  - sudo apt-get install php-pear php5-dev
  - pecl install oauth-1.2.3
  - sh -c "if [ ! -e apcu-4.0.2 ]; then wget http://pecl.php.net/get/apcu-4.0.2.tgz && tar -xzf apcu-4.0.2.tgz ; fi"
  - sh -c "cd apcu-4.0.2 && phpize && ./configure && make && sudo make install"
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sh -c "if [ ! -e redis-2.2.7 ]; then wget http://pecl.php.net/get/redis-2.2.7.tgz && tar -xzf redis-2.2.7.tgz ; fi"
  - sh -c "cd redis-2.2.7 && phpize && ./configure && make && sudo make install"
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/Test/travis/lite_php_browscap.ini /home/travis/browscap.ini
  - echo 'browscap = "/home/travis/browscap.ini"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo service apache2 restart
  - composer install --prefer-dist --no-interaction --no-dev
  - mkdir ./app/tmp
  - chmod -R 777 ./app/tmp
  - mkdir -p build/logs
  - cd ./app

script:
  - ./Console/cake test app AllTests --stderr --coverage-clover ../build/logs/clover.xml --configuration ../phpunit.xml.dist
  - cd ../

after_script:
  - php Vendor/bin/coveralls -v

before_deploy:
  - php Vendor/bin/coveralls -v

notifications:
  slack: goalous:JkI6FxdrZDzE1gILR6qTJ69p
  email: false

deploy:
  - provider: opsworks
    access-key-id: AKIAJHXVNZZEOX3TD5BA
    secret-access-key: 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
    app-id: 786fd3c0-1b5f-49d9-b707-27dba2909c84
    wait-until-deployed: false
    on:
      branch: release
  - provider: opsworks
    access-key-id: AKIAJHXVNZZEOX3TD5BA
    secret-access-key: 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
    app-id: 35e69705-18d9-4c45-81eb-7e02e0c61fdc
    wait-until-deployed: true
    on:
      branch: prep-lp-page
  - provider: opsworks
    access-key-id: AKIAJHXVNZZEOX3TD5BA
    secret-access-key: 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
    app-id: feaeb538-35a5-4a1c-bab7-01a70c666987
    wait-until-deployed: true
    on:
      branch: hotfix
  - provider: opsworks
    access-key-id: AKIAJHXVNZZEOX3TD5BA
    secret-access-key: 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
    app-id: 77c4fc53-40c3-4a73-b532-18d5ef1beff7
    wait-until-deployed: true
    on:
      branch: master
